# -*- coding: utf-8 -*-
"""covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SITGIt2M3aph0sT4U4oDNl_0Xa2u--U-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("raw_data_final.csv")

#print(list(data.columns))

data = data[data['subdivisionId'] == "KA"]
df1 = data[['date', 'female_count', 'male_count']]
#print(df.head())
df2 = data[['date', 'age_count_below_10','age_count_10-30','age_count_30-60','age_count_above_60',]]
#print(df2.head())

plt.figure(figsize=(10, 8))
plt.plot(df['date'],df['female_count'], 'b-', label = 'Female Count')
plt.plot(df['date'],df['male_count'], 'r-', label = 'Male Count')
plt.xlabel('Date'); plt.ylabel('Count'); plt.title('Male vs Female Affected')
plt.legend();

plt.figure(figsize=(10, 8))
plt.plot(df2['date'],df2['age_count_below_10'], 'b-', label = 'Age below 10')
plt.plot(df2['date'],df2['age_count_10-30'], 'r-', label = 'Age 10 - 30')
plt.plot(df2['date'],df2['age_count_30-60'], 'y-', label = 'Age 30 - 60')
plt.plot(df2['date'],df2['age_count_above_60'], 'g-', label = 'Age above 60')
plt.xlabel('Date'); plt.ylabel('Count'); plt.title('Age wise Time Series')
plt.legend();